- hosts: all
  vars:
    - user: hadmin
    - basedir: "/opt/{{user}}"
    - tcp_ports:         
      - "50070/tcp"
      - "8088/tcp"
      - "16010/tcp"
      - "4242/tcp"
      - "8070/tcp"
    - jdk:
        version: java-1.8.0-openjdk
    - hadoop:
        home: "{{basedir}}/hadoop"
        version: hadoop-2.7.4
        hdfs_properties:
          - { name: dfs.replication, value: 1 }
          - { name: dfs.name.dir, value: "file:///{{basedir}}/hadoop/data/hdfs/namenode" }
          - { name: dfs.data.dir, value: "file:///{{basedir}}/hadoop/data/hdfs/datanode" }
        core_properties:
          - { name: fs.default.name, value: "hdfs://{{ansible_default_ipv4.address}}:9000" }
        mapred_properties:
          - { name: mapreduce.framework.name, value: yarn }
    - hbase:
        home: "{{basedir}}/hbase"
        ver: 1.2.6
        version: hbase-1.2.6
        hbase_properties:
          - { name: hbase.rootdir, value: "hdfs://{{ansible_default_ipv4.address}}:9000/hbase" }
          - { name: hbase.cluster.distributed, value: "true" }
          - { name: hbase.zookeeper.property.dataDir, value: "hdfs://{{ansible_default_ipv4.address}}:9000/zookeeper" }
          - { name: hbase.zookeeper.quorum, value: "{{ansible_default_ipv4.address}}" }
          - { name: hbase.zookeeper.property.clientPort, value: "2181" }
    - opentsdb:
        home: "{{basedir}}/opentsdb"
        ver: v2.3.0
        version: opentsdb-2.3.0
        staticroot: "{{basedir}}/opentsdb/build/staticroot"
        cachedir: "{{basedir}}/opentsdb/cache"
        zk_quorum: "{{ansible_default_ipv4.address}}"
        network_bind: "{{ansible_default_ipv4.address}}"
        port: 4242
    - bosun:
        home: "{{basedir}}/bosun"
  roles:
    - { role: common, tags: ['common','hadoop','hbase','opentsdb','bosun'], become: yes }
    - { role: golang, tags: ['golang',bosun], become: yes }
    - { role: hadoop, tags: ['hadoop'] }
    - { role: hbase, tags: ['hbase'] }
    - { role: opentsdb, tags: ['opentsdb'] }
    - { role: bosun, tags: ['bosun'] }
