- name: Install Required Packages
  yum: 
    name: "{{item}}"
    state: present
  with_items:
    - "{{jdk.version}}"
    - "{{jdk.version}}-devel"
    - git
    - "@Development tools"
    - firewalld
    
- name: Find JAVA_HOME
  shell: "find /usr/lib/jvm/*{{jdk.version}}* -maxdepth 0 -type d"
  register: jdk_path

- set_fact:
    jdk_home: "{{jdk_path.stdout}}"
    
- name: Open TCP Ports
  firewalld:
    port: "{{item}}"
    permanent: true
    state: enabled
    zone: public
    immediate: yes
  with_items:
    - "50070/tcp"
    - "8088/tcp"
    - "16010/tcp"
    - "4242/tcp"