- name: Install Required Packages
  yum: 
    name: "{{item}}"
    state: present
  with_items:
    - "{{jdk.version}}"
    - "{{jdk.version}}-devel"
    - git
    - "@Development tools"
    - firewalld
    
- name: Find JAVA_HOME
  shell: "find /usr/lib/jvm/*{{jdk.version}}* -maxdepth 0 -type d"
  register: jdk_path

- set_fact:
    jdk_home: "{{jdk_path.stdout}}"
    
- name: Open TCP Ports
  firewalld:
    port: "{{item}}"
    permanent: true
    state: enabled
    zone: public
    immediate: yes
  ignore_errors: yes
  with_items: "{{tcp_ports}}"

- name: Create User for Hadoop
  user: 
    name: "{{user}}"
    generate_ssh_key: yes

- name: Create {{basedir}} directory
  file:
    path: "{{basedir}}"
    state: directory
    mode: 0755
    owner: "{{user}}"
    group: "{{user}}" 
  
